name: Scrape Bookdepository website

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
      
  schedule:
    - cron: "0 */8 * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm config set registry http://registry.npmjs.org
          npm install cheerio -E
          npm run scrapper
          git config user.name bookreads-bot
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] Update Database"
          git push origin main
